#!/usr/bin/sh
PROJECT_DIR="../project1"

echo ----------------------------------------------------------------
echo ----------------------------------------------------------------
cat "$PROJECT_DIR/documentation.txt"
echo ----------------------------------------------------------------
echo Running Make
(
    cd "$PROJECT_DIR" || exit 1
    make
)
echo
echo
echo ----------------------------------------------------------------
echo Testing with No Command-line args
"$PROJECT_DIR/project1"
echo ----------------------------------------------------------------
echo Testing with Correct SIC Assembly
"$PROJECT_DIR/project1" "test1.sic"
echo ----------------------------------------------------------------
echo Testing case 2  SIC Program Has CLOOP defined twice DUPLICATE SYMBOL
"$PROJECT_DIR/project1" "test2.sic"
echo ----------------------------------------------------------------
echo Testing case 3  SIC Program Has  Invalid Hex Constant
"$PROJECT_DIR/project1" "test3.sic"
echo ----------------------------------------------------------------
echo Testing case 4  SIC Program Has Symbol Name that is an assembler Directive BYTE
"$PROJECT_DIR/project1" "test4.sic"
echo ----------------------------------------------------------------
echo Testing case 5  SIC Program Starts at Hex 8000. No room left in SIC memory.
"$PROJECT_DIR/project1" "test5.sic"
echo ----------------------------------------------------------------
echo Testing case 6  Long Byte Constant that is ok. Pass 1 should be ok
"$PROJECT_DIR/project1" "test6.sic"
echo ----------------------------------------------------------------
echo Testing case 7  Has blank lines - violates specification. Pass1 should stop
"$PROJECT_DIR/project1" "test7.sic"
echo ----------------------------------------------------------------
echo Testing case 8 WORD Constant Exceeds 24 bit limitation
"$PROJECT_DIR/project1" "test8.sic"
echo ----------------------------------------------------------------
echo Testing case 9 Program Has Invalid Symbol Name
"$PROJECT_DIR/project1" "test9.sic"
echo ----------------------------------------------------------------
echo Testing case 10 Program Does not fit in SIC Memory
"$PROJECT_DIR/project1" "test10.sic"

