#!/usr/bin/sh

echo ----------------------------------------------------------------
echo ----------------------------------------------------------------
cat documentation.txt
echo ----------------------------------------------------------------
echo Running Make
make
echo
echo
echo ----------------------------------------------------------------
echo Testing with Correct SIC Assembly
./project2 test21.sic

echo ----------TEST 21 Object File-------------------------------------------
cat test21.sic.obj
echo ----------------------------------------------------------------
echo Testing case 2  SIC Program to copy a string using indexed addressing
./project2 test22.sic
echo ----------TEST 22 Object File-------------------------------------------

cat test22.sic.obj
echo ----------------------------------------------------------------
echo Testing case 3  SIC Program Has  Invalid Hex Constant  
./project2 test23.sic
echo ----------------------------------------------------------------
echo Testing case 4  SIC Program HasSymbol Name that is an assembler Directive BYTE 
./project2 test24.sic
echo ----------------------------------------------------------------
echo Testing case 5  SIC Program Missing START DIRECTIVE   
./project2 test25.sic
cat test25.sic.obj
echo ----------------------------------------------------------------
echo Testing case 6  Long Byte Constant that is ok.  Has undefined symbol, Pass 2 should stop  
./project2 test26.sic
echo ----------------------------------------------------------------
echo Testing case 7 
./project2 test27.sic
echo ----------TEST 27 Object File-------------------------------------------
cat test27.sic.obj
echo ----------------------------------------------------------------
echo Testing case 8
./project2 test28.sic
echo ----------TEST 28 Object File-------------------------------------------
cat test28.sic.obj
echo ----------------------------------------------------------------
echo Testing case 9   
./project2 test29.sic
echo ----------TEST 29 Object File-------------------------------------------
cat test29.sic.obj
echo ----------------------------------------------------------------
echo Testing case 10  
./project2 test30.sic
echo ----------TEST 30 Object File-------------------------------------------
cat test30.sic.obj

